// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huqromtnbpbpwvhemgrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1cXJvbXRuYnBicHd2aGVtZ3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzkyNjgsImV4cCI6MjA2ODY1NTI2OH0.2jdtQtY7bUOXLLxVrv5USkOz0Wk2NClSOKo1puuUQwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});